[package]
name = "arena-city"
version = "0.1.2-alpha.0"
edition = "2021"
publish = false

[features]
serde = []

[dependencies]
parking_lot = "0.12"
serde_crate = { version = "1", optional = true, package = "serde" }
